# Generated by Django 4.2.11 on 2024-04-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=8, unique=True, verbose_name="Username"),
        ),
    ]
