# Generated by Django 4.2.11 on 2024-04-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_asistencia_alter_poapasistencia_tabla_asistencia_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='poapasistencia',
            unique_together={('alumno', 'tabla_asistencia')},
        ),
    ]
